### ISSUE TITLE
Implement API with the basic elasticsearch.js's

### ISSUE THREAD

**Issue by jhogoforbroke** [jhogoforbroke/elastic_node_lab#3]
# Description

Implements the basic functionalists for [elasticsearch.js@16.5.0](https://www.npmjs.com/package/elasticsearch).

## Tasks

- [ ] Ping Action
- [ ] Create Index Action
- [ ] Index Ecistis Action
- [ ] Put Mapping Action
- [ ] Add Dcouments Action
- [ ] update Documents Action
- [ ] Search Action
- [ ] Delete Document Action
- [ ] Delete All Action
